cloud:
  aws:
    credentials:
      accessKey: AKIASXRVBQ2MSEW33BEX
      secretKey: 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
    s3:
      bucket: uckgisagi-bucket
    region:
      static: ap-northeast-2
    stack:
      auto: false
