spring:
  config:
    activate:
      on-profile: prod

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://uckgisagi.cqkpidwwievn.ap-northeast-2.rds.amazonaws.com/uckgisagi_prod?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: uckgisagi_admin
    password: uckgisagi_password

  jpa:
    database: mysql
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 1000

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
    com.amazonaws.util.EC2MetadataUtils: error