cloud:
  aws:
    credentials:
      accessKey: AKIASXRVBQ2MYAEWXMFQ
      secretKey: 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
    s3:
      bucket: uckgisagi-bucket
    region:
      static: ap-northeast-2
    stack:
      auto: false
